# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: Numpy.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

Numpy es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, numpy posee una documentación muy amplia que es SIEMPRE RECOMENDABLE consultar.

# Clase 4: Introduccion a NumPy

# Ejercicios

In [1]:
# PUNTO 1 - Crear un arreglo de ceros de longitud 12
import numpy as np


In [2]:
# PUNTO 2 - Crear un arreglo de ceros de longitud 12
arreglo = np.zeros(12) 
arreglo

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# PUNTO 3 - Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
arreglo[4]=10
print(arreglo)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.  0.  0.]


In [4]:
# PUNTO 4 - Crear un arreglo que tenga los números del 10 al 49
np.arange (10,50,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
# PUNTO 5 - Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
arreglo4 = np.arange(9).reshape(3, 3) #Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
print(arreglo4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
# PUNTO 5 - Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
arreglo5 = np.random.rand(100) 
print(arreglo5)

[5.14631949e-02 3.36957485e-01 8.67332384e-01 5.26686212e-01
 8.79327785e-01 5.78280368e-01 5.24370002e-01 3.37253266e-01
 5.21394649e-01 4.32039394e-01 1.66167826e-01 6.59592082e-01
 4.45586354e-01 5.02348899e-01 1.25066649e-01 3.37873411e-01
 3.03009063e-01 1.75711097e-01 3.57159184e-01 2.07157307e-01
 2.14228892e-01 3.14926474e-01 1.15315335e-01 4.46921841e-01
 3.23245504e-01 8.10009969e-02 2.86820054e-01 9.19851090e-02
 4.33713304e-01 5.54798469e-01 1.90400501e-01 8.08472629e-01
 2.44275536e-02 7.47445289e-01 3.23337146e-01 7.24320332e-03
 9.86374966e-03 4.34953357e-01 3.00630876e-01 2.37503367e-02
 2.83376525e-01 4.38305753e-01 1.96663239e-01 6.10911298e-01
 2.72524812e-01 4.96422159e-01 1.87019790e-01 7.16314180e-01
 1.67525222e-01 6.36288861e-01 4.88502315e-01 7.22053042e-01
 7.44139758e-01 9.85187046e-01 9.74136368e-01 3.22684331e-01
 9.26848022e-02 3.12417723e-01 4.06539539e-01 8.53515325e-01
 7.64844620e-01 7.00046030e-01 5.48985552e-01 5.08570431e-01
 1.31347660e-01 6.607465

In [7]:
np.mean(arreglo5)

0.42580967357633065

In [8]:
np.var(arreglo5)

0.07552163611657446

In [11]:
# PUNTO 6 - Calcular la media de un arreglo usando np.sum
arreglo_media = np.array([1, 2, 3, 4, 5]) 
media = np.sum(arreglo_media) / arreglo_media.size
print(media)

3.0


In [12]:
# PUNTO 7 - Calcular la varianza de un arreglo usando np.sum y np.mean
arreglo_varianza = np.array([1, 2, 3, 4, 5]) 
media = np.mean(arreglo_varianza)
varianza = np.sum((arreglo_media - media) ** 2) / arreglo_varianza.size
print(arreglo_varianza)
print(media)
print(varianza)

[1 2 3 4 5]
3.0
2.0


In [13]:
 # PUNTO 8 - Crear un array de números aleatorios usando np.random.randn
arreglo8 = np.random.rand(30)
print(arreglo8)

[0.18022832 0.68537816 0.6339479  0.7304017  0.47436185 0.81755645
 0.95640688 0.87664714 0.93224685 0.84027704 0.88525174 0.72936513
 0.13844433 0.26632953 0.86521686 0.51352997 0.58434767 0.50499581
 0.66670943 0.32640808 0.26493877 0.09665038 0.56375662 0.75587475
 0.28894787 0.83543109 0.58144184 0.63570017 0.97822314 0.8220871 ]
